# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AwdIeSSTea23wA2PMB6bPvhoWswHR8Jc

Libraries
"""

#OpenCV
import cv2
#NumPy
import numpy as np
#Pandas
import pandas as pd

#Read the image
img = cv2.imread(r"E:\Projects\Color Recognition\color_image2.jpeg")

#Set the indices for the datset
index=["color", "color_name", "hex", "R", "G", "B"]

#Read the colors data set
csv = pd.read_csv(r'E:\Projects\Color Recognition\colors.csv', names=index, header=0)

#Initialize the needed global variables
r = g = b = xpos = ypos = clicked = 0

"""Color Recognition Function"""

def recognize_color(R,G,B):
    min = 10000
    for i in range(len(csv)):
        d = abs(R- int(csv.loc[i,"R"])) + abs(G- int(csv.loc[i,"G"]))+ abs(B- int(csv.loc[i,"B"]))
        if(d<=min):
            min = d
            cname = csv.loc[i,"color_name"]
    return cname

"""Mouse Click Function"""

def click(event, x, y, flags, param):
    if event == cv2.EVENT_LBUTTONDBLCLK:
        global b,g,r,xpos,ypos,clicked
        clicked = 1
        xpos = x
        ypos = y
        b,g,r = img[y,x]
        b = int(b)
        g = int(g)
        r = int(r)

"""Application Window"""

cv2.namedWindow('Color Recognition App')
cv2.setMouseCallback('Color Recognition App', click)

while(1):
    cv2.imshow("Color Recognition App",img)
    if (clicked):
   
        #cv2.rectangle(image, startpoint, endpoint, color, thickness)-1 fills entire rectangle 
        cv2.rectangle(img,(20,20), (750,60), (b,g,r), -1)

        #Creating text string to display( Color name and RGB values )
        text = recognize_color(r,g,b) + ' R='+ str(r) +  ' G='+ str(g) +  ' B='+ str(b)
        
        #cv2.putText(img,text,start,font(0-7),fontScale,color,thickness,lineType )
        cv2.putText(img, text,(50,50),2,0.8,(255,255,255),2,cv2.LINE_AA)
        
        #For very light colours we will display text in black colour
        if(r+g+b>=600):
            cv2.putText(img, text,(50,50),2,0.8,(0,0,0),2,cv2.LINE_AA)
            
        clicked=0

#Break the loop when user hits 'esc' key    
    if cv2.waitKey(20) & 0xFF ==27:
        break
cv2.destroyAllWindows()